name: 'VigileGuard Security Audit'
description: 'Run security audit checks on your infrastructure and applications'
author: 'VigileGuard Team'

branding:
  icon: 'shield'
  color: 'red'

inputs:
  target:
    description: 'Target to scan (hostname, IP address, or URL)'
    required: true

  config-file:
    description: 'Path to VigileGuard configuration file'
    required: false
    default: '.vigileguard.yml'

  checkers:
    description: 'Comma-separated list of security checkers to run'
    required: false
    default: 'all'

  fail-on-critical:
    description: 'Fail the build on CRITICAL severity issues'
    required: false
    default: 'true'

  fail-on-high:
    description: 'Fail the build on HIGH severity issues'
    required: false
    default: 'false'

  output-format:
    description: 'Output format (json, html, cli)'
    required: false
    default: 'json'

  upload-results:
    description: 'Upload results as GitHub Actions artifacts'
    required: false
    default: 'true'

  comment-pr:
    description: 'Comment scan results on pull requests'
    required: false
    default: 'false'

  api-endpoint:
    description: 'VigileGuard API endpoint URL (for centralized scanning)'
    required: false

  api-key:
    description: 'API key for VigileGuard API (use secrets)'
    required: false

  webhook-url:
    description: 'Webhook URL for notifications (Slack, Teams, Discord)'
    required: false

  severity-threshold:
    description: 'Minimum severity level to report (critical, high, medium, low)'
    required: false
    default: 'medium'

  timeout:
    description: 'Scan timeout in seconds'
    required: false
    default: '300'

outputs:
  scan-id:
    description: 'Unique scan identifier'

  report-path:
    description: 'Path to generated report file'

  critical-count:
    description: 'Number of critical issues found'

  high-count:
    description: 'Number of high severity issues found'

  medium-count:
    description: 'Number of medium severity issues found'

  low-count:
    description: 'Number of low severity issues found'

  total-issues:
    description: 'Total number of security issues found'

  compliance-score:
    description: 'Overall compliance score (0-100)'

  scan-status:
    description: 'Scan completion status (passed, failed, warning)'

  artifacts-url:
    description: 'GitHub Actions artifacts URL for detailed reports'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    VIGILEGUARD_TARGET: ${{ inputs.target }}
    VIGILEGUARD_CONFIG: ${{ inputs.config-file }}
    VIGILEGUARD_CHECKERS: ${{ inputs.checkers }}
    VIGILEGUARD_FAIL_CRITICAL: ${{ inputs.fail-on-critical }}
    VIGILEGUARD_FAIL_HIGH: ${{ inputs.fail-on-high }}
    VIGILEGUARD_FORMAT: ${{ inputs.output-format }}
    VIGILEGUARD_UPLOAD: ${{ inputs.upload-results }}
    VIGILEGUARD_PR_COMMENT: ${{ inputs.comment-pr }}
    VIGILEGUARD_API_ENDPOINT: ${{ inputs.api-endpoint }}
    VIGILEGUARD_API_KEY: ${{ inputs.api-key }}
    VIGILEGUARD_WEBHOOK_URL: ${{ inputs.webhook-url }}
    VIGILEGUARD_SEVERITY_THRESHOLD: ${{ inputs.severity-threshold }}
    VIGILEGUARD_TIMEOUT: ${{ inputs.timeout }}
    GITHUB_TOKEN: ${{ github.token }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_SHA: ${{ github.sha }}
    GITHUB_REF: ${{ github.ref }}
    GITHUB_EVENT_NAME: ${{ github.event_name }}
    GITHUB_PR_NUMBER: ${{ github.event.number }}
    GITHUB_WORKSPACE: ${{ github.workspace }}